### ISSUE TITLE
Astronaut faces

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#293]
This finally occurred to me today.  Two of the astronauts in the roster, Ed Dwight and Robert Lawrence, were black, and noticeably so.  It would be handy if the face image would reflect the color of their skin.  I had a look in data/images, but there are only 86 images when the roster hosts 106 per side.  I wonder, are the faces assigned randomly?

**Comment by rnyoakum** [comment]
Currently, faces are assigned randomly. See ast1.cpp:

```
Data->P[plr].Pool[i + Data->P[plr].AstroCount].Face = brandom(77);

if (Data->P[plr].Pool[i + Data->P[plr].AstroCount].Sex == 1) {
    Data->P[plr].Pool[i + Data->P[plr].AstroCount].Face = 77 + brandom(8);
}
```

**Comment by peyre** [comment]
Ah, figures.  So not only would we have to create faces for the two guys, but we'd have to make a programming exception for them.  Too bad really.

**Comment by peyre** [comment]
Come to think of it, there are also a couple cosmonauts in the roster of east Asian descent (one Vietnamese, one Mongolian).  I wonder if we could use the Sex variable to also indicate races that need a different picture; Sex = 2 could indicate black and Sex = 3 Asian.

In case we should do something like this, I've created some faces that could be used for them.

**Comment by rnyoakum** [comment]
It would be *possible* to use sex, but that might cause some complications elsewhere; it would require examining every piece of code where gender is checked. I'm finishing off the Downgrades (Manned -> Unmanned) after which I plan to tackle data storage. Currently, the game still relies on .dat files for the rosters, but there's unused code for switching the rosters over to Json. Once the switch to Json occurs, it will be possible to add fields to roster entries, which could include race or even specifying a preferred face image.

**Comment by peyre** [comment]
Very nice!  Hey maybe we could add a field for Service to populate that field in the recruitment screen (#165).

**Comment by peyre** [comment]
I'm not sure how this happened, but the game seems now to assign male and female faces randomly, as well.

![Female pic](https://user-images.githubusercontent.com/3118014/107993031-dbe21c80-6f8e-11eb-86a6-c6b9513e4e4c.png)
![Male pic](https://user-images.githubusercontent.com/3118014/107993032-dc7ab300-6f8e-11eb-8280-ab109b61224d.png)

**Comment by peyre** [comment]
Hehe, Buzz looks so cute!

![Aldrin](https://user-images.githubusercontent.com/3118014/122683270-faf9f080-d1b2-11eb-89c9-80c0959eeb64.png)

**Comment by peyre** [comment]
And J.Dietrich looks so rugged!

![J Dietrich is a man](https://user-images.githubusercontent.com/3118014/140867682-00de4533-799c-44af-9a9d-ec0a0dcace5a.png)

**Comment by rnyoakum** [comment]
Fixed the gender issue. I accidentally swapped the order around in astronaut assignment when I was making some code more readable last year. I looked for the problem several times since, and must have checked that line a half-dozen times and always read it the way I _expected_ it to be; I'd gotten convinced there was something really weird going on. It should be fine now, but since astronaut/cosmonaut faces are assigned at recruitment it won't resolve the issue for any currently afflicted 'nauts.

**Comment by peyre** [comment]
Wow, thanks!  That was a bit of weirdness.

**Comment by peyre** [comment]
It looks like this is happening again (or still happening?).

![Female naut](https://user-images.githubusercontent.com/3118014/212563618-217e3889-8333-46d6-9212-0c9564ff2d68.png)

**Comment by peyre** [comment]
I'm seeing this again.

![MaleFemale astronaut](https://user-images.githubusercontent.com/3118014/229309964-b3842d27-a01d-4e9a-8b0f-fcfa6c2a8835.png)

**Comment by peyre** [comment]
Now that the 'naut roster has been made into a JSON and we've added the Service characteristic, I've also added a Race characteristic.  I also have pictures for black and Asian 'nauts.  So if we should want to implement different racial faces sometimes, the game is ready on the data side.

**Comment by peyre** [comment]
Bummer, I thought I could add the faces and have ast1.cpp select them if Race > 0, but while compiling it says 

`/home/leon/raceintospace/src/game/ast1.cpp:630:13: error: ‘struct Astros’ has no member named ‘Race’; did you mean ‘Face’?
  630 |     recruit.Race = Men[candidate].Race;
      |             ^~~~
      |             Face
/home/leon/raceintospace/src/game/ast1.cpp:647:22: error: ‘struct Astros’ has no member named ‘Race’; did you mean ‘Face’?
  647 |     switch (&recruit.Race) {
      |                      ^~~~
      |                      Face
make[2]: *** [src/game/CMakeFiles/raceintospace.dir/build.make:146: src/game/CMakeFiles/raceintospace.dir/ast1.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:433: src/game/CMakeFiles/raceintospace.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
`

I added **ar(CEREAL_NVP(Race));** to data.h, and struct ManPool now shows
`int8_t Sex, Service, Race, Cap, LM, EVA, Docking, Endurance;`

And I added this to ast1.cpp
`    recruit.Race = Men[candidate].Race;`
and (I know it's horribly kludgy)
`    switch (recruit.Race) {
    case 0:
        recruit.Face = recruit.Sex ? (77 + brandom(8)) : brandom(77);
        break;
    case 1:
        if (&recruit.Name[0] == "DWIGHT") {
            recruit.Face = 87;
        } else if (&recruit.Name[0] == "LAWRENCE") {
            recruit.Face = 88;
        } else {
            recruit.Face = 87 + brandom(1);
        } break;
    case 2:
        if (&recruit.Name[0] == "GURRAGCHAA") {
            recruit.Face = 89;
        } else if (&recruit.Name[0] == "TUAN") {
            recruit.Face = 90;
        } else {
            recruit.Face = 89 + brandom(1);
        } break;
    }'

**Comment by hweimer** [comment]
I think there are some lines missing from the compiler error. Other than that, your changes look correct to me.

**Comment by peyre** [comment]
Very strange!  Maybe this is like with the Service category, where I was almost there but missing one little thing or whatever.  I'll email you the files in case you care to look them over.

**Comment by peyre** [comment]
Hang on, I think this has been implemented.

**Comment by peyre** [comment]
Uh oh, I'm still seeing the occasional anomaly.  I wonder though - this happened with a Group IV female astronaut, and there were never women in Groups IV and V.  The other two women I recruited came out fine, but not Jerri Sloan.

<img width="650" height="424" alt="Image" src="https://github.com/user-attachments/assets/532d790f-9a46-4eda-b018-f2ae52ce2f00" />
